apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPSPHostNetworkingPorts
metadata:
  name: k8spsphostnetworkingports
spec:
  enforcementAction: deny
  match:
    kinds:
    - apiGroups: ["app"]
      kinds: ["Deployment"]
  parameters:
    hostNetwork: false
