apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: demo
  name: crud-pods
subjects:
- kind: User
  name: alice
roleRef:
  kind: Role
  name: pod-crud 

apiVerison: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sre-crud-pods
subjects:
- kind: User
  name: bob
roleRef:
  kind: ClusterRole
  name: cluster-pod-crud

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sre-read-pods
subjects:
- kind: User
  name: carol
roleRef: 
  kind: ClusterRole
  name: cluster-pod-reader