apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-password-externalsecret
spec:
  refreshInterval: 30s
  refreshPolicy: Periodic

  secretStoreRef:
    name: aws-secretsmanager-store
    kind: SecretStore

  target:
    name: my-k8s-db-secret
    creationPolicy: Owner
    deletionPolicy: Retain

  data:
    - secretKey: password
      remoteRef:
        key: my-aws-secret-name
        property: password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
