apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-password-externalsecret
spec:
  refreshInterval: "30s" # Keeps rotation time under 60 seconds
  secretStoreRef:
    name: aws-secretsmanager-store
    kind: SecretStore
  target:
    name: my-k8s-db-secret # This is the K8s Secret that ESO will create automatically
    creationPolicy: Owner
  data:
  - secretKey: password # Key name inside the K8s Secret
    remoteRef:
      key: my-aws-secret-name # Tên secret trên AWS Secrets Manager
      property: password # Key inside AWS Secrets Manager JSON
