apiVersion: policy.sigstore.dev/v1beta1
kind: ClusterImagePolicy
metadata:
  name: require-signed-w10-api
spec:
  mode: enforce
  images:
    - glob: "ghcr.io/feniksxshi/w10-api*"
  authorities:
    - name: authority-0
      key:
        data: |
          -----BEGIN PUBLIC KEY-----
          MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEt23SPvOpMux4oPZisUP5cOObRhcW
          FcckzZWg469zNSTxJhzqjOLw7MA/v3X3TmykMBDxt35HTSwV4Vru7SBDHg==
          -----END PUBLIC KEY-----